app/controllers/members_controller.rb, config/routes.rb, test/controllers/members_controller_test.rb
Please check this over. Thanks.
=> Members initial route and controller

app/controllers/communities_controller.rb, app/models/community.rb, app/models/fixture.rb, app/models/league.rb, app/models/member.rb, app/models/member_guess.rb, app/models/team.rb, app/views/communities/index.html.erb, app/views/communities/show.html.erb
=> models and index scaffold

app/views/communities/_table.html.erb, app/views/communities/show.html.erb
=> fixed show page

app/models/fixture.rb, app/models/league.rb, app/models/team.rb, db/migrate/20211123130132_create_teams.rb, db/migrate/20211123130158_create_fixtures.rb, db/migrate/20211123144939_add_references_to_tables.rb, db/schema.rb, db/seeds.rb
Refactored database and then added 500 lines to the seeds file ;)
=> Database refactor and seeds.rb extravaganza

app/controllers/communities_controller.rb, app/models/member.rb, app/views/communities/_overall_table.html.erb, app/views/communities/_table.html.erb, app/views/communities/_weekly_table.html.erb, app/views/communities/index.html.erb, app/views/communities/show.html.erb
=> completed two tables, will need to work with new data today

app/controllers/communities_controller.rb, app/controllers/members_controller.rb, app/views/communities/_overall_table.html.erb, app/views/communities/_weekly_table.html.erb, app/views/communities/show.html.erb, config/routes.rb
=> finished weekly tables

app/assets/stylesheets/components/_form.scss, app/views/communities/_form.html.erb, app/views/communities/show.html.erb, app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb
=> fixed forms

db/seeds.rb
=> changed name to Jonathan for first user

app/assets/stylesheets/application.scss, app/assets/stylesheets/pages/_show.scss, app/views/communities/show.html.erb, app/views/pages/_home_navbar.html.erb
=> fixed show page styling

app/assets/stylesheets/components/_index.scss, app/views/communities/index.html.erb
=> index title styling

app/assets/stylesheets/components/_index.scss, app/views/communities/index.html.erb
Put links in communities member is a part of  into cards using home page image,
=> communities index page changes

app/controllers/member_guesses_controller.rb, app/javascript/controllers/submit_scores_controller.js, app/views/communities/_form.html.erb
I put in a Stimulus button which iterates through each form and submits all the scores in one.
=> stimulus for submit button

app/assets/stylesheets/components/_index.scss, app/controllers/communities_controller.rb, app/javascript/controllers/clipboard_controller.js, app/models/community.rb, app/models/member.rb, app/views/communities/index.html.erb
Copy to clipboard button implemented minus styling and controller tweaked. User journey complete!
=> copy to clipboard button

app/javascript/packs/application.js, app/views/communities/_overall_table.html.erb, app/views/communities/_weekly_table.html.erb, app/views/communities/show.html.erb
=> finished tooltips

app/assets/stylesheets/pages/_show.scss, app/views/communities/_results.html.erb, app/views/communities/show.html.erb
=> first outline of results page

app/views/communities/_results.html.erb, app/views/communities/show.html.erb
=> fixed button bug on show page

app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/pages/_index-page.scss, app/assets/stylesheets/pages/_show.scss, app/views/communities/_overall_table.html.erb, app/views/communities/_weekly_table.html.erb, app/views/communities/index.html.erb, app/views/communities/show.html.erb
=> started redesign of index

app/assets/stylesheets/pages/_index-page.scss, app/views/communities/index.html.erb
=> fixed bug on index page

app/assets/stylesheets/config/_fonts.scss, app/assets/stylesheets/pages/_index-page.scss, app/assets/stylesheets/pages/_show.scss, app/views/communities/index.html.erb, app/views/communities/show.html.erb
=> fixed repeating background photo

app/views/communities/_form.html.erb
=> Form alignment and button disabled

app/assets/stylesheets/pages/_home.scss, app/views/pages/home.html.erb
Made background image full screen, placed cards over them, resized create and join buttons to be equal size
=> home page styling

app/assets/stylesheets/components/_form.scss, app/views/communities/_form.html.erb
=> form css updated

app/javascript/controllers/submit_scores_controller.js
=> adding time to submit

app/assets/stylesheets/components/_form.scss
Cursor for form and darker input box border when clicked.
=> last min styling

app/assets/stylesheets/pages/_index-page.scss
=> centered league name on cards
